### ISSUE TITLE
install Rpackage of RSQLite trigger on miniconda

### ISSUE THREAD

**Issue by honghh2018** [r-dbi/RSQLite#367]
Hi @All,
     It was very weird on the RSQLite install, because of the header file, boost/detail/fenv.hpp, had exist on my system, it still complaint about that file  boost/detail/fenv.hpp can not be found.
     the file on my CENTOS 7  locating below:
     
![image](https://user-images.githubusercontent.com/41668708/114841538-89946f00-9e0a-11eb-80fe-5da29657b43b.png)
     The package RSQLite install by miniconda env in R 4.0.3, but the error make me confuse.
      How can i fix this error?
      any advice would be appreciated.
      hanhuihong

**Comment by fxi** [comment]
Too much "Only necessary files", @krlmlr ? ( 0b4fde34 )
 
I got the same error on alpine 3.12.1, R 4.1.0, RSQLite 2.2.7

```sh
84.32 vendor/boost/math/tools/config.hpp:408:13: fatal error: boost/detail/fenv.hpp: No such file or directory
84.32   408 |    #include <boost/detail/fenv.hpp>
84.32       |             ^~~~~~~~~~~~~~~~~~~~~~~
84.32 compilation terminated.
````

Reproducible example : 

```Dockerfile
# Dockerfile
ARG R_VERSION="4.1.0"

FROM rhub/r-minimal:${R_VERSION} as build_r

ENV R_PACKAGES_DATE="2021-06-15"

RUN echo "local({ \
rep <- getOption('repos'); \
rep['CRAN'] <- 'https://mran.microsoft.com/snapshot/$R_PACKAGES_DATE'; \
options(Ncpus = $(nproc --all)) ; \
options(repos = rep) \
})" > .Rprofile

RUN apk add --no-cache --virtual build_deps \
  linux-headers \
  build-base \
  R-dev \
  sqlite-dev

RUN Rscript -e ' install.packages("RSQLite")'

CMD ["Rscript","-e","library(RSQLite)"]

```

```sh
docker build  --progress plain --tag rsqlite_toremove .
```

Works fine with BH_1.75.0-0. pre 0b4fde34 , RSQLite 2.2.5  : 

```Dockerfile
ARG R_VERSION="4.1.0"

FROM rhub/r-minimal:${R_VERSION} as build_r

ENV R_PACKAGES_DATE="2021-04-01"

RUN echo "local({ \
rep <- getOption('repos'); \
rep['CRAN'] <- 'https://mran.microsoft.com/snapshot/$R_PACKAGES_DATE'; \
options(Ncpus = $(nproc --all)) ; \
options(repos = rep) \
})" > .Rprofile

RUN apk add --no-cache --virtual build_deps \
  linux-headers \
  build-base \
  R-dev \
  sqlite-dev

RUN Rscript -e ' install.packages("RSQLite")'

CMD ["Rscript","-e","library(RSQLite)"]


```

**Comment by krlmlr** [comment]
Thanks, confirmed. More flexible `Dockerfile`:

```docker
# Dockerfile
ARG R_VERSION="4.1.0"

FROM rhub/r-minimal:${R_VERSION} as build_r

ENV R_PACKAGES_DATE="2021-06-15"

RUN echo "local({ \
rep <- getOption('repos'); \
rep['CRAN'] <- 'https://mran.microsoft.com/snapshot/$R_PACKAGES_DATE'; \
options(Ncpus = $(nproc --all)) ; \
options(repos = rep) \
})" > .Rprofile

RUN apk add --no-cache --virtual build_deps \
  linux-headers \
  build-base \
  R-dev \
  sqlite-dev

RUN apk add --no-cache git

RUN git clone https://github.com/r-dbi/RSQLite

RUN Rscript -e 'install.packages(c("remotes", "pkgbuild"))'

RUN Rscript -e 'remotes::install_deps("RSQLite", dependencies = c("Imports", "LinkingTo"))'

RUN Rscript -e 'remotes::install_local("RSQLite")'

CMD ["Rscript","-e","library(RSQLite)"]
```

**Comment by krlmlr** [comment]
Thanks for the reports. Releasing to CRAN very soon.
