### ISSUE TITLE
Version 2.3.10 ignores additional INCLUDE_DIR

### ISSUE THREAD

**Issue by rattei** [r-dbi/RSQLite#592]
The installation of RSQLite 2.3.10 fails when SQLite is in a custom path. Neither exporting PKG_CONFIG_PATH=/opt/sqlite/3.49.1/lib/pkgconfig nor R CMD INSTALL --configure-vars="LIB_DIR='/opt/sqlite/3.49.1/lib' INCLUDE_DIR='/opt/sqlite/3.49.1/include'" RSQLite_2.3.10.tar.gz work. The compilation stops at ext-csv.c

gcc -I"/lisc/app/R/4.2.3/lib64/R/include" -DNDEBUG -Ivendor -DRSQLITE_USE_BUNDLED_SQLITE -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_STAT4 -DSQLITE_SOUNDEX -DSQLITE_USE_URI=1 -DSQLITE_MAX_LENGTH=2147483647 -DHAVE_USLEEP=1 -I'/lisc/app/R/4.2.3/lib64/R/library/plogr/include' -I'/lisc/app/R/4.2.3/lib64/R/library/cpp11/include' -I/usr/local/include  -fvisibility=hidden -fpic  -g -O2  -c ext-csv.c -o ext-csv.o
In file included from ext-csv.c:5:
vendor/extensions/csv.c:42:10: fatal error: sqlite3ext.h: No such file or directory
   42 | #include <sqlite3ext.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.

The problem did not exist in 2.3.9.

**Comment by krlmlr** [comment]
Thanks. This might be due to https://github.com/r-dbi/RSQLite/pull/587, triggered by #512. Would you like to do check or do a Git bisect to identify the cause?

RSQLite comes with recent SQLite (3.49.1), so there's no need to point to a custom installation. Is this a requirement for you?

Does the build works without `--configure-vars` ? It fails on CI/CD currently...

**Comment by rattei** [comment]
The build also fails without --configure-vars. The error message is the same: sqlite3ext.h is missing. That's why I tried to configure the additional include path.

**Comment by krlmlr** [comment]
Thanks, confirmed with gcc on Ubuntu 24.04, works with clang. Updating on GitHub soon, do you think it's worth doing an emergency CRAN release?

**Comment by rattei** [comment]
Thanks for the update. The issue if not urgent at all from our side. I had patched the sources (to insert the full path to sqlite3ext.h), and thereby installed the package.

**Comment by krlmlr** [comment]
RSQLite 2.3.11 is on CRAN.

**Comment by rattei** [comment]
Thanks for the quick solution.  I can confirm that RSQLite 2.3.11 successfully compiles in our setting.
